const cart=[];const qs=s=>document.querySelector(s);const qsa=s=>[...document.querySelectorAll(s)];
function money(n){return n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function toast(){const t=qs('#toast');t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),1800)}
function addItem(name,price,details=''){cart.push({name,price:Number(price),details});renderCart();toast()}
function renderCart(){qs('#cartCount').textContent=cart.length;const box=qs('#cartItems');if(!cart.length){box.innerHTML='<div class="empty">Seu carrinho está vazio.<br><small>Escolha algo delicioso no cardápio.</small></div>';qs('#cartTotal').textContent=money(0);return}box.innerHTML=cart.map((x,i)=>`<div class="cart-line"><div><b>${x.name}</b>${x.details?`<small>${x.details}</small>`:''}</div><strong>${money(x.price)}</strong></div>`).join('');qs('#cartTotal').textContent=money(cart.reduce((s,x)=>s+x.price,0))}
qsa('[data-add]').forEach(b=>b.addEventListener('click',()=>addItem(b.dataset.add,b.dataset.price)));
qsa('.tab').forEach(b=>b.addEventListener('click',()=>{qsa('.tab').forEach(x=>x.classList.remove('active'));qsa('.menu-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');qs('#tab-'+b.dataset.tab).classList.add('active')}));
let size='250ml',base='Açaí',basePrice=10;
qsa('#sizesChoice .choice').forEach(b=>b.addEventListener('click',()=>{qsa('#sizesChoice .choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');size=b.dataset.size;basePrice=Number(b.dataset.base);updateBuilder()}));
qsa('.base.choice').forEach(b=>b.addEventListener('click',()=>{qsa('.base.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');base=b.dataset.baseType;if(base==='Cupuaçu'){const prices={'250ml':13,'300ml':14,'400ml':16,'500ml':18};basePrice=prices[size]}else{const prices={'250ml':10,'300ml':12,'400ml':13,'500ml':14};basePrice=prices[size]}updateBuilder()}));
function updateBuilder(){const count=qsa('.toppings input:checked').length;qs('#builderPrice').textContent=money(basePrice+count*2)}
qsa('.toppings input').forEach(x=>x.addEventListener('change',updateBuilder));
qs('#addCustom').addEventListener('click',()=>{const tops=qsa('.toppings input:checked').map(x=>x.value);addItem(`${base} ${size}`,basePrice+tops.length*2,tops.length?`Acompanhamentos: ${tops.join(', ')}`:'Sem acompanhamentos');qsa('.toppings input').forEach(x=>x.checked=false);updateBuilder()});
qs('#openCart').addEventListener('click',()=>qs('#cartOverlay').classList.add('open'));qs('#closeCart').addEventListener('click',()=>qs('#cartOverlay').classList.remove('open'));qs('#cartOverlay').addEventListener('click',e=>{if(e.target.id==='cartOverlay')qs('#cartOverlay').classList.remove('open')});qs('#clearCart').addEventListener('click',()=>{cart.length=0;renderCart()});
qs('#checkout').addEventListener('click',()=>{if(!cart.length){toast();return}const lines=cart.map(x=>`• ${x.name} — ${money(x.price)}${x.details?' | '+x.details:''}`).join('%0A');const total=money(cart.reduce((s,x)=>s+x.price,0));const msg=`Olá! Quero fazer um pedido na Casa do Açaí:%0A%0A${lines}%0A%0A*Total: ${total}*%0A%0AComo faço para finalizar?`;window.open('https://wa.me/5517981817159?text='+msg,'_blank')});
qs('#menuBtn').addEventListener('click',()=>{const n=qs('.navlinks');n.style.display=n.style.display==='flex'?'none':'flex';if(n.style.display==='flex'){n.style.position='absolute';n.style.top='68px';n.style.left='0';n.style.right='0';n.style.background='#fff';n.style.padding='20px';n.style.flexDirection='column';n.style.boxShadow='0 15px 30px #0001'}});
renderCart();updateBuilder();
